//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boundary
    {
        public Boundary()
        {
            this.Beacons = new HashSet<Beacon>();
            this.Devices = new HashSet<Device>();
        }
    
        public int boundary_id { get; set; }
        public string boundary_name { get; set; }
        public Nullable<System.DateTime> boundary_from { get; set; }
        public Nullable<System.DateTime> boundary_to { get; set; }
        public Nullable<bool> boundary_enabled { get; set; }
    
        public virtual ICollection<Beacon> Beacons { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
