//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public Floor()
        {
            this.Beacons = new HashSet<Beacon>();
            this.Records = new HashSet<Record>();
        }
    
        public int floor_id { get; set; }
        public string floor_name { get; set; }
        public byte[] floor_image { get; set; }
    
        public virtual ICollection<Beacon> Beacons { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
