//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_info { get; set; }
        public byte[] group_icon { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
