//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public int sector_id { get; set; }
        public Nullable<int> beacon_id { get; set; }
        public Nullable<double> sector_min_RSSI { get; set; }
        public Nullable<double> sector_max_RSSI { get; set; }
        public string sector_area_on_map { get; set; }
    
        public virtual Beacon Beacon { get; set; }
    }
}
